const lightTheme = {
  'html': 'html-light',
  'body': 'body-light',
  'container-header': 'container-header-light',
  'logo': 'logo-light',
  'nav': 'nav-light',
  'theme-switcher': 'theme-switcher-light',
  'hamburger-button': 'hamburger-button-light',
  'container-hero': 'container-hero-light',
  'button': 'button-light',
  'button_colored': 'button_colored-light',
  'section-title': 'section-title-light',
  'portfolio-tagline': 'portfolio-tagline-light',
  'skill-item': 'skill-item-light',
  'skill-description': 'skill-description-light',
  'skills': 'skills-light',
  'wrapper': 'wrapper-light',
  'price-list__card': 'price-list__card-light',
  'card-price': 'card-price-light',
  'text-gold': 'text-gold',
  'contacts': 'contacts-light',
  'contact-form': 'contact-form-light',
  'social-link': 'social-link-light',
  'credits': 'credits-light',
  'footer': 'footer-light',
}

export default lightTheme;
